version: '3.3'

services:
  go:
    build:
      context: .
      dockerfile:  ./docker/golang/Dockerfile
    container_name: backend
    ports:
      - 8082:8082
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./backend:/go/src/backend
    working_dir: /go/src/backend
    tty: true

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

