version: '3.1'

# volumes:
#   ignore:

services:
  vue:
    build:
      context: ./docker/vue
    container_name: frontend
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # command: sh -c "npm run serve"

  go:
    build:
      context: .
      dockerfile:  ./docker/golang/Dockerfile
    container_name: backend
    ports:
      - 8082:8082
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./backend:/go/src/backend
      # mount対象から除外
      # - ignore:/go/src/docker/vue
      # - ignore:/go/src/docker/nginx
    working_dir: /go/src/backend
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

